# Generated by Django 6.0.6 on 2026-07-08 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_jobinterest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobopening',
            name='roles_responsibilities',
        ),
    ]
