# Generated by Django 6.0.6 on 2026-07-20 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_remove_jobopening_roles_responsibilities'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobopening',
            name='amount_to_pay',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='jobopening',
            name='backdoor_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='jobopening',
            name='opening_type',
            field=models.CharField(choices=[('Regular', 'Regular'), ('Backdoor', 'Backdoor')], default='Regular', max_length=20),
        ),
    ]
