# Generated by Django 6.0.6 on 2026-07-20 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_jobopening_amount_to_pay_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobopening',
            name='amount_to_pay',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
