# Generated by Django 6.0.6 on 2026-07-22 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_alter_jobopening_amount_to_pay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobopening',
            name='amount_to_pay',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
