# Generated by Django 6.0.6 on 2026-06-20 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_emailotp_attempts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adminprofile',
            old_name='default_code',
            new_name='access_code',
        ),
        migrations.AddField(
            model_name='customuser',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
