# Generated by Django 6.0.6 on 2026-07-07 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='employment_status',
            field=models.CharField(blank=True, choices=[('Currently Working', 'Currently Working'), ('Fresher', 'Fresher'), ('Not Working', 'Not Working')], max_length=30),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='institute',
            field=models.CharField(blank=True, choices=[('SSS', 'SSS'), ('Sainora', 'Sainora'), ('SankthiDB Technology', 'SankthiDB Technology'), ('TesDB Academy', 'TesDB Academy')], max_length=50),
        ),
    ]
