# Generated by Django 6.0.6 on 2026-07-07 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_customuser_employment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='resume',
            field=models.FileField(blank=True, upload_to='resumes/'),
        ),
    ]
