# Generated by Django 6.0.6 on 2026-07-07 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_customuser_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='employment_status',
            field=models.CharField(blank=True, choices=[('Currently Working', 'Currently Working'), ('Fresher', 'Fresher')], max_length=30),
        ),
    ]
