# Generated by Django 6.0.6 on 2026-07-08 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_customuser_employment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='employment_status',
            field=models.CharField(blank=True, choices=[('Currently Working', 'Currently Working'), ('Not Working', 'Not Working'), ('Fresher', 'Fresher')], max_length=30),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='institute',
            field=models.CharField(blank=True, choices=[('SSS', 'SSS'), ('Sainora', 'Sainora'), ('SankthiDB Technology', 'SankthiDB Technology'), ('TesDB Academy', 'TesDB Academy'), ('Others', 'Others')], max_length=50),
        ),
    ]
